// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0E-INceo7CTJ3SdU3YTIHkU3XId94bQM',
    appId: '1:659465217763:web:92588d9d7f3ec99f3707d6',
    messagingSenderId: '659465217763',
    projectId: 'chatappflutter-f0267',
    authDomain: 'chatappflutter-f0267.firebaseapp.com',
    storageBucket: 'chatappflutter-f0267.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCR6xQ36-Ki9M-wkNxE-vRYipYeEqzediQ',
    appId: '1:659465217763:android:0ad96a8e579c9bc43707d6',
    messagingSenderId: '659465217763',
    projectId: 'chatappflutter-f0267',
    storageBucket: 'chatappflutter-f0267.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBlQEyMxtytjtV__dOQXLWN_Lh4arWLYE',
    appId: '1:659465217763:ios:3bb9106ad57efe003707d6',
    messagingSenderId: '659465217763',
    projectId: 'chatappflutter-f0267',
    storageBucket: 'chatappflutter-f0267.appspot.com',
    iosBundleId: 'com.example.chatappFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBlQEyMxtytjtV__dOQXLWN_Lh4arWLYE',
    appId: '1:659465217763:ios:4c0562dda78f23343707d6',
    messagingSenderId: '659465217763',
    projectId: 'chatappflutter-f0267',
    storageBucket: 'chatappflutter-f0267.appspot.com',
    iosBundleId: 'com.example.chatappFirebase.RunnerTests',
  );
}
